const columns = [
    { name: "NAME", uid: "name", sortable: true },
    { name: "DESCRIPTION", uid: "description", sortable: true },
    { name: "DICOUNT TYPE", uid: "discount", sortable: true },
    { name: "PERCENTAGE", uid: "percentage" },
    { name: "CREATED AT", uid: "created" },
    { name: "EXPIRED AT", uid: "expired", sortable: true },
    { name: "ACTIONS", uid: "actions" },
  ];
  
  const statusOptions = [
    { name: "Active", uid: "active" },
    { name: "Paused", uid: "paused" },
    { name: "Vacation", uid: "vacation" },
  ];
  
  const promotions = [
    {
      id: 1,
      name: "Alice Johnson",
      description: "Summer Collection",
      discount: "Seasonal Sale",
      percentage: "10%",
      created: "2024-06-01",
      expired: "2024-07-01",
      actions: "active",
    },
    {
      id: 2,
      name: "Bob Smith",
      description: "Winter Sale",
      discount: "Clearance",
      percentage: "20%",
      created: "2024-05-15",
      expired: "2024-06-15",
      actions: "paused",
    },
    {
      id: 3,
      name: "Charlie Davis",
      description: "Spring Collection",
      discount: "Flash Sale",
      percentage: "15%",
      created: "2024-05-20",
      expired: "2024-06-20",
      actions: "vacation",
    },
    {
        id: 4,
        name: "David Wilson",
        description: "Fall Collection",
        discount: "End of Season",
        percentage: "25%",
        created: "2024-07-10",
        expired: "2024-08-10",
        actions: "active",
      },
      {
        id: 5,
        name: "Emma Brown",
        description: "Holiday Specials",
        discount: "Markdowns",
        percentage: "30%",
        created: "2024-08-01",
        expired: "2024-09-01",
        actions: "paused",
      },
      {
        id: 6,
        name: "Frank Miller",
        description: "Back to School",
        discount: "Special Offers",
        percentage: "20%",
        created: "2024-07-15",
        expired: "2024-08-15",
        actions: "vacation",
      },
      {
        id: 7,
        name: "Grace Lee",
        description: "Christmas Sale",
        discount: "Holiday",
        percentage: "30%",
        created: "2024-12-10",
        expired: "2024-12-25",
        actions: "active",
      },
      {
        id: 8,
        name: "Henry White",
        description: "New Year Discounts",
        discount: "Festival",
        percentage: "35%",
        created: "2024-12-31",
        expired: "2024-01-10",
        actions: "paused",
      },
      {
        id: 9,
        name: "Isla Black",
        description: "Valentine's Day",
        discount: "Romantic",
        percentage: "14%",
        created: "2024-02-01",
        expired: "2024-02-14",
        actions: "active",
      },
      {
        id: 10,
        name: "Jack Davis",
        description: "Easter Offers",
        discount: "Holiday Special",
        percentage: "20%",
        created: "2024-03-15",
        expired: "2024-04-01",
        actions: "vacation",
      },
      {
        id: 11,
        name: "Kelly Brown",
        description: "Back to School",
        discount: "Seasonal",
        percentage: "25%",
        created: "2024-08-01",
        expired: "2024-09-01",
        actions: "active",
      },
      {
        id: 12,
        name: "Liam Miller",
        description: "Halloween Sale",
        discount: "Spooky",
        percentage: "30%",
        created: "2024-10-15",
        expired: "2024-11-01",
        actions: "paused",
      },
      {
        id: 13,
        name: "Mia Wilson",
        description: "Independence Day",
        discount: "Patriotic",
        percentage: "20%",
        created: "2024-07-01",
        expired: "2024-07-05",
        actions: "active",
      },
      {
        id: 14,
        name: "Noah Martinez",
        description: "Labor Day",
        discount: "Workforce",
        percentage: "18%",
        created: "2024-09-01",
        expired: "2024-09-07",
        actions: "vacation",
      },
      {
        id: 15,
        name: "Olivia Anderson",
        description: "Thanksgiving Deals",
        discount: "Harvest",
        percentage: "22%",
        created: "2024-11-10",
        expired: "2024-11-25",
        actions: "active",
      },
      {
        id: 16,
        name: "Paul Garcia",
        description: "Winter Clearance",
        discount: "Season End",
        percentage: "45%",
        created: "2024-01-10",
        expired: "2024-01-31",
        actions: "paused",
      },
      {
        id: 17,
        name: "Quinn Taylor",
        description: "Summer Bonanza",
        discount: "Hot Deals",
        percentage: "28%",
        created: "2024-06-15",
        expired: "2024-07-15",
        actions: "active",
      },
      {
        id: 18,
        name: "Ryan Thomas",
        description: "New Year Bash",
        discount: "Celebration",
        percentage: "35%",
        created: "2024-12-25",
        expired: "2025-01-05",
        actions: "vacation",
      },
      {
        id: 19,
        name: "Sophia Moore",
        description: "Spring Discounts",
        discount: "Blossom",
        percentage: "12%",
        created: "2024-03-01",
        expired: "2024-03-31",
        actions: "active",
      },
      {
        id: 20,
        name: "Tyler Jackson",
        description: "Festival of Colors",
        discount: "Celebration",
        percentage: "25%",
        created: "2024-03-10",
        expired: "2024-03-20",
        actions: "paused",
      },
  ];
  
  export { columns, promotions, statusOptions };
  