export type ShopDetail = {
  name: string;
  slug: string;
  address: string;
  description: string;
  phoneNumber: string;
  email: string;
  isDeleted: boolean;
  isDisable: string;
  openAt: string;
  closeAt: string;
  shopType: string;
  profile: string;
  cover: string;
  owners: [string];
  location: string;
  createdAt: string;
  updatedAt: string;
  createdBy: string;
  updateBy: string;
};
