export const MemberList = [
  {
    img: '/images/members/votey.jpg',
    role: 'Frontend developer',
    name: 'Hom Pheakakvotey',
    facebook: 'https://www.facebook.com/polsokhann',
    instagram: 'https://www.instagram.com/polsokhann',
    google: 'https://www.google.com/search?q=polsokhann',
  },
  {
    img: '/images/members/soben.jpg',
    role: 'Full Stack developer',
    name: 'On Soben',
    facebook: 'https://www.facebook.com/polsokhann',
    instagram: 'https://www.instagram.com/polsokhann',
    google: 'https://www.google.com/search?q=polsokhann',
  },
  {
    img: '/images/members/sokkhann.jpg',
    role: 'Frontend developer',
    name: 'Pol Sokhann',
    facebook: 'https://www.facebook.com/polsokhann',
    instagram: 'https://www.instagram.com/polsokhann',
    google: 'https://www.google.com/search?q=polsokhann',
  },
  {
    img: '/images/members/vandeth.jpg',
    role: 'Backend developer',
    name: 'Art Vandeth',
    facebook: 'https://www.facebook.com/polsokhann',
    instagram: 'https://www.instagram.com/polsokhann',
    google: 'https://www.google.com/search?q=polsokhann',
  },
  {
    img: '/images/members/naikim.jpg',
    role: 'Frontend developer',
    name: 'Leang Naikim',
    facebook: 'https://www.facebook.com/polsokhann',
    instagram: 'https://www.instagram.com/polsokhann',
    google: 'https://www.google.com/search?q=polsokhann',
  },
  {
    img: '/images/members/layhak.jpg',
    role: 'Full Stack developer',
    name: 'Heng Layhak',
    facebook: 'https://www.facebook.com/polsokhann',
    instagram: 'https://www.instagram.com/polsokhann',
    google: 'layhakheng@gmail.com',
  },
  {
    img: '/images/members/nak.jpg',
    role: 'Frontend developer',
    name: 'Sol Vathanak',
    facebook: 'https://www.facebook.com/polsokhann',
    instagram: 'https://www.instagram.com/polsokhann',
    google: 'https://www.google.com/search?q=polsokhann',
  },
];
